### ISSUE TITLE
Streaming support

### ISSUE THREAD

**Issue by excelosaurus** [skbkontur/ZstdNet#11]
Is streaming support planned, or was it left out due to technical limitations?

**Comment by dscheg** [comment]
Sorry, no streaming support planned at the moment.

**Comment by excelosaurus** [comment]
Is it strictly due to time constraints, or is it technically challenging/impractical? I'd like to help but not if you already know it's a dead end.

**Comment by borzunov** [comment]
There was no technical limitations, so you can try to implement it :)

**Comment by dimzon** [comment]
streaming support:
https://gist.github.com/dimzon/4e7f076dd59fa6df2a3207e1fa6ac406

demo:
```
static void Main(string[] args)
        {
            Console.WriteLine(Zstd.GetVersionNumber());
            Console.WriteLine(Zstd.GetVersionString());
            Console.WriteLine(Zstd.GetMaxCompessionLevel());

            var b = File.ReadAllBytes(@"c:\app\testbigfile");
            var memoryStream = new MemoryStream();
            var memoryStream2 = new MemoryStream();
            using (var x = new Zstd.ZStdOutputStream(memoryStream,2, true))
                x.Write(b, 0, b.Length);
            memoryStream.Position = 0;
            using (var x = new Zstd.ZStdInputStream(memoryStream, true ))
                x.CopyTo(memoryStream2);

            var b2 = memoryStream2.ToArray();

            if (b.Length != b2.Length)
            {
                Console.WriteLine("size differs {0} {1}", b.Length, b2.Length);
                return;
            }

            for (int i = 0; i < b.Length; i++)
            {
                if(b[i]==b2[i]) continue;
                Console.WriteLine("value differs");
                return;
            }
        }
    }
```

**Comment by jenspetervester** [comment]
@dimzon Thanks a lot! Just what I have been needing for quite some time.

**Comment by bp74** [comment]
I created my own ZStandard .Net library with support for streaming and dictionaries.
I will use this library in an important project, so it will be well maintained in the future.
https://www.nuget.org/packages/Zstandard.Net/

**Comment by AlgorithmsAreCool** [comment]
I'm working on streaming support. I should have a PR shortly.

**Comment by dscheg** [comment]
released
