### ISSUE TITLE
Why not on nuget?

### ISSUE THREAD

**Issue by Rajivhost** [skbkontur/ZstdNet#2]
Hi,
Why we can not have this through nuget?

Best regards,
Rajiv.

**Comment by lukasz-pyrzyk** [comment]
Exactly! CC @borzunov

**Comment by lukasz-pyrzyk** [comment]
@dscheg ?

**Comment by borzunov** [comment]
I am sorry for the late response.

The package has been [published](https://www.nuget.org/packages/ZstdNet/).
