### ISSUE TITLE
ThreadSafety issue in DictBuilder.TrainFromBuffer

### ISSUE THREAD

**Issue by EamonNerbonne** [skbkontur/ZstdNet#20]
DictBuilder.TrainFromBuffer appears to deadlock occasionally when called concurrently.

Example that causes deadlocks fairly reliably:

```C#
var anArr = Enumerable.Range(0, 200000).Select(n=>(byte)(n*n)).ToArray();
var arrs= Enumerable.Range(0,200).Select(i=>anArr.Skip(i*3).Take(i*5+1000).ToArray()).ToArray();
Console.WriteLine("start");
var dicts = Enumerable.Range(0,20)
    .AsParallel() //relevant line A
    .Select(dictI=> {
        var subset = arrs
            .Skip(dictI*7%37).Take(100 + dictI*37%53).ToArray() //relevant line B
            ;
        return DictBuilder.TrainFromBuffer(subset, 9812);
    }).ToArray();
Console.WriteLine("sometimes deadlocks");
```
I pretty much never see the program reach "sometimes deadlocks".

Executing the program without parallelism (comment out line A) works reliably, as does building the same dictionary in all threads (comment out line B).

**Comment by dscheg** [comment]
Seems to be no longer reproducible in recent versions of `libzstd`. Internal implementation of `ZDICT_trainFromBuffer` has changed quite a lot. Please reopen if reproduced on libzstd >= v1.4.5. Also note that there is a [bug](https://github.com/facebook/zstd/issues/2371) in current libzstd v1.4.5 that can cause `ZDICT_trainFromBuffer` to break on some inputs. In particular, it breaks on the example code above.
Test: https://github.com/skbkontur/ZstdNet/blob/ce98e630714cf444f3155055416906deceaace83/ZstdNet.Tests/Binding_Tests.cs#L474

**Comment by EamonNerbonne** [comment]
This does not appear to have been released to nuget yet: https://www.nuget.org/packages/ZstdNet/ - is that upcoming?

**Comment by dscheg** [comment]
I'm going to release this with a recompiled and patched `libzstd` probably this week

**Comment by EamonNerbonne** [comment]
Assuming an upstream fix will arrive eventually, a plain global lock might suffice, though obviously that's not ideal, perf-wise.
