### ISSUE TITLE
zstd 1.1.3 support

### ISSUE THREAD

**Issue by mailmaldi** [skbkontur/ZstdNet#9]
Any plans to support zstd 1.1.3 ?

**Comment by extesy** [comment]
Any chance @borzunov or @dscheg could update ZstdNet to the latest version (1.1.4 at the moment)? If this project is abandoned then I'm going to fork it so that I could keep it up to date.

**Comment by borzunov** [comment]
Hi @extesy,

Sorry, but my internship in SKB Kontur has ended. We need to wait for a @dscheg's response to get information about the future of this repository.

**Comment by dscheg** [comment]
Hi, I'm going to update ZstdNet in a week.

**Comment by dscheg** [comment]
Updated sources to libzstd.dll 1.2.0 dev 29297c67. Nuget package I'll update after 1.2.0 release.

**Comment by extesy** [comment]
@dscheg zstd 1.2.0 has been released: https://github.com/facebook/zstd/releases

**Comment by dscheg** [comment]
@extesy done

**Comment by lukasz-pyrzyk** [comment]
Nice job guys :)
